### ISSUE TITLE
Set up all third party accounts 

### ISSUE THREAD

**Issue by rihakhan** [Scout-NU/vital-site#2]
Use this email [vital.northeastern@gmail.com ](url) to set up Contentful and any other third-party apps we will be using throughout the semester. Make sure to coordinate with Heenal directly in our client slack channel or through Slack DM (Riha can also coordinate this) for account confirmations and such.

**Comment by Ryanjso** [comment]
Waiting on Heenal to complete registration https://nuscout.slack.com/archives/C01KNNSCVT4/p1614208437001400
